name: Set up pulumi stack
inputs:
  version:
    required: true
    type: string
  stack:
    required: true
    type: string
  token:
    required: true
    type: string
  passphrase:
    required: false
    type: string
  config:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: pulumi/setup-pulumi@v2
    - name: pulumi stack
      run: |
        mkdir -p configs
        echo "${{ inputs.config }}" > configs/Pulumi.${{ inputs.stack }}.yaml
        pulumi stack select ${{ inputs.stack }}
        pulumi config set version ${{ inputs.version }}
        pulumi config set sha ${GITHUB_SHA::6}
      working-directory: ./deploy/pulumi
      shell: bash
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.token }}
        PULUMI_CONFIG_PASSPHRASE: ${{ inputs.passphrase }}
