version: '2'

services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: db
      MARIADB_DATABASE: db
      MARIADB_USER: db
      MARIADB_PASSWORD: db
    volumes:
      - db-data:/var/lib/mysql
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: none
  adminer:
    image: 'adminer'
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
  kowl:
    image: 'quay.io/cloudhut/kowl:master'
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
  runner:
    image: node:16-alpine
    command: ./entrypoint.sh
    working_dir: /usr/src/runner
    user: node
    depends_on:
      - db
      - kafka
    volumes:
      - ./packages/runner:/usr/src/runner
  cli:
    image: node:16-alpine
    working_dir: /usr/src/api
    depends_on:
      - db
      - kafka
    volumes:
      - ./packages/api:/usr/src/api
  mailer:
    image: node:16-alpine
    command: ./entrypoint.sh
    working_dir: /usr/src/mailer
    depends_on:
      - db
      - kafka
      - mailhog
    volumes:
      - ./packages/mailer:/usr/src/mailer
  api:
    image: node:16-alpine
    command: ./entrypoint.sh
    working_dir: /usr/src/api
    depends_on:
      - db
      - kafka
    volumes:
      - ./packages/api:/usr/src/api
  app:
    image: node:16-alpine
    command: ./entrypoint.sh
    working_dir: /usr/src/app
    depends_on:
      - db
      - kafka
      - runner
    volumes:
      - ./packages/app:/usr/src/app
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - app
      - mailhog
      - pgadmin
      - kowl

volumes:
  kafka-data:
  db-data:
  zookeeper-data:
