version: "2"

services:
  db:
    image: mariadb:10.8
    environment:
      - MARIADB_ROOT_PASSWORD=db
      - MARIADB_DATABASE=db
      - MARIADB_USER=db
      - MARIADB_PASSWORD=db
    volumes:
      - db-data:/var/lib/mysql
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
  kafka:
    image: bitnami/kafka:3.0.1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
  mailhog:
    image: mailhog/mailhog:v1.0.1
    logging:
      driver: none
  adminer:
    image: adminer:4.8.1
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
  kowl:
    image: quay.io/cloudhut/kowl:master
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
  runner:
    build:
      context: ./packages/runner
    user: node
    environment:
      - DB_HOSTNAME=db
      - DB_NAME=db
      - DB_USERNAME=db
      - DB_PASSWORD=db
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - db
      - kafka
  cli:
    build:
      context: ./packages/cli
    command: ./entrypoint.sh
    environment:
      - DB_HOSTNAME=db
      - DB_NAME=db
      - DB_USERNAME=db
      - DB_PASSWORD=db
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - db
      - kafka
  mailer:
    build:
      context: ./packages/mailer
    environment:
      - KAFKA_BROKERS=kafka:9092
      - APP_URL=http://localhost:8080/
      - MAILER_HOST=mailhog
      - MAILER_PORT=1025
    depends_on:
      - kafka
      - mailhog
  api:
    build:
      context: ./packages/api
    environment:
      - DB_HOSTNAME=db
      - DB_NAME=db
      - DB_USERNAME=db
      - DB_PASSWORD=db
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - db
      - kafka
  app:
    build:
      context: ./packages/app
    depends_on:
      - db
      - kafka
      - runner
  nginx:
    build:
      context: ./packages/nginx
    ports:
      - 8080:80
    depends_on:
      - api
      - app
      - mailhog
      - pgadmin
      - kowl

volumes:
  kafka-data:
  db-data:
  zookeeper-data:
