name: Publish Package
inputs:
  package_name:
    required: true
    type: string
  token:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        check-name: Conventional Commits check
        repo-token: ${{ inputs.token }}
        wait-interval: 10
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - uses: docker/build-push-action@v2
      with:
        tags: ghcr.io/andersevenrud/microservice-rnd-${{inputs.package_name}}:latest
        context: ./packages/${{inputs.package_name}}
