name: Test Package
inputs:
  package_name:
    required: true
    type: string
  coverage_token:
    required: false
    type: string
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache-dependency-path: packages/${{inputs.package_name}}/package-lock.json
    - run: npm ci
      shell: bash
      working-directory: ./packages/${{inputs.package_name}}
    - run: npm run lint
      shell: bash
      working-directory: ./packages/${{inputs.package_name}}
    - run: npm run typecheck
      shell: bash
      working-directory: ./packages/${{inputs.package_name}}
    - if: ${{ inputs.coverage_token == '' }}
      run: npm run test
      shell: bash
      working-directory: ./packages/${{inputs.package_name}}
    - if: ${{ inputs.coverage_token != '' }}
      run: npm run test -- --coverage
      shell: bash
      working-directory: ./packages/${{inputs.package_name}}
    - if: ${{ inputs.coverage_token != '' }}
      uses: codecov/codecov-action@v2
      with:
        token: ${{inputs.coverage_token}}
        directory: ./packages/${{inputs.package_name}}/coverage/
        name: ${{inputs.package_name}}
        flags: ${{inputs.package_name}}
