apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: rnd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      restartPolicy: Always
      containers:
        - name: api
          image: ghcr.io/andersevenrud/microservice-rnd-api:latest
          imagePullPolicy: Always
          ports:
            - name: public
              containerPort: 8080
            - name: health
              containerPort: 8081
          env:
            - name: DB_HOSTNAME
              value: db
            - name: DB_NAME
              value: db
            - name: DB_PASSWORD
              value: db
            - name: DB_USERNAME
              value: db
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: HEALTH_READINESS_PROBE_DELAY
              value: "30000"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
