apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    job: cleanup
  name: cleanup
  namespace: rnd
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cli
            image: microservice-rnd-cli
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - npm run cleanup
          restartPolicy: OnFailure
