apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    job: cleanup
  name: cleanup
  namespace: rnd
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cli
            image: ghcr.io/andersevenrud/microservice-rnd-cli:latest
            command: ["npm", "run", "cleanup"]
            env:
              - name: DB_HOSTNAME
                value: db
              - name: DB_NAME
                value: db
              - name: DB_PASSWORD
                value: db
              - name: DB_USERNAME
                value: db
              - name: KAFKA_BROKERS
                value: kafka:9092
