apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    backend: db
  name: db-data
  namespace: rnd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    backend: db-pod
