apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    backend: kafka
  name: kafka-data
  namespace: rnd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
