apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    backend: zookeeper
  name: zookeeper-data
  namespace: rnd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
