apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi","ops":"cert"},"name":"selfsigned-ca","namespace":"rnd"},"spec":{"commonName":"selfsigned-ca","isCA":true,"issuerRef":{"group":"cert-manager.io","kind":"ClusterIssuer","name":"selfsigned-issuer"},"privateKey":{"algorithm":"ECDSA","size":256},"secretName":"selfsigned-root-secret"}}
  labels:
    app.kubernetes.io/managed-by: pulumi
    ops: cert
  name: selfsigned-ca
  namespace: rnd
spec:
  commonName: selfsigned-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: selfsigned-root-secret
