apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"ClusterIssuer","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi","ops":"cert"},"name":"selfsigned-cluster-issuer","namespace":"rnd"},"spec":{"selfSigned":{}}}
  labels:
    app.kubernetes.io/managed-by: pulumi
    ops: cert
  name: selfsigned-cluster-issuer
  namespace: rnd
spec:
  selfSigned: {}
