apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi","job":"cleanup"},"name":"cleanup","namespace":"rnd"},"spec":{"failedJobsHistoryLimit":0,"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"command":["npm","run","cleanup"],"env":[{"name":"DB_HOSTNAME","value":"db"},{"name":"DB_NAME","value":"db"},{"name":"DB_PASSWORD","value":"db"},{"name":"DB_USERNAME","value":"db"},{"name":"KAFKA_BROKERS","value":"kafka:9092"}],"image":"ghcr.io/andersevenrud/microservice-rnd-cli:latest","name":"cli"}],"restartPolicy":"OnFailure"}}}},"schedule":"0 * * * *","successfulJobsHistoryLimit":0}}
  labels:
    app.kubernetes.io/managed-by: pulumi
    job: cleanup
  name: cleanup
  namespace: rnd
spec:
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - npm
            - run
            - cleanup
            env:
            - name: DB_HOSTNAME
              value: db
            - name: DB_NAME
              value: db
            - name: DB_PASSWORD
              value: db
            - name: DB_USERNAME
              value: db
            - name: KAFKA_BROKERS
              value: kafka:9092
            image: ghcr.io/andersevenrud/microservice-rnd-cli:latest
            name: cli
          restartPolicy: OnFailure
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 0
