apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"Issuer","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi","ops":"cert"},"name":"selfsigned-issuer","namespace":"rnd"},"spec":{"ca":{"secretName":"selfsigned-root-secret"}}}
  labels:
    app.kubernetes.io/managed-by: pulumi
    ops: cert
  name: selfsigned-issuer
  namespace: rnd
spec:
  ca:
    secretName: selfsigned-root-secret
