apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi","job":"migrations"},"name":"db-migrations","namespace":"rnd"},"spec":{"template":{"spec":{"containers":[{"command":["npm","run","migrate"],"env":[{"name":"DB_HOSTNAME","value":"db"},{"name":"DB_NAME","value":"db"},{"name":"DB_PASSWORD","value":"db"},{"name":"DB_USERNAME","value":"db"},{"name":"KAFKA_BROKERS","value":"kafka:9092"}],"image":"ghcr.io/andersevenrud/microservice-rnd-cli:latest","name":"cli-db-migrations"}],"restartPolicy":"OnFailure"}}}}
  labels:
    app.kubernetes.io/managed-by: pulumi
    job: migrations
  name: db-migrations
  namespace: rnd
spec:
  template:
    spec:
      containers:
      - command:
        - npm
        - run
        - migrate
        env:
        - name: DB_HOSTNAME
          value: db
        - name: DB_NAME
          value: db
        - name: DB_PASSWORD
          value: db
        - name: DB_USERNAME
          value: db
        - name: KAFKA_BROKERS
          value: kafka:9092
        image: ghcr.io/andersevenrud/microservice-rnd-cli:latest
        name: cli-db-migrations
      restartPolicy: OnFailure
