apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"api-health","app.kubernetes.io/managed-by":"pulumi"},"name":"api-health","namespace":"rnd"},"spec":{"ports":[{"port":8081}],"selector":{"app":"api-pod"},"sessionAffinity":"None"}}
  labels:
    app: api-health
    app.kubernetes.io/managed-by: pulumi
  name: api-health
  namespace: rnd
spec:
  ports:
  - port: 8081
  selector:
    app: api-pod
  sessionAffinity: None
