name: Deploy Preview
on:
  workflow_dispatch:
  pull_request:
    paths:
      - deploy/pulumi/**
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache-dependency-path: deploy/pulumi/package-lock.json
      - run: npm ci
        working-directory: ./deploy/pulumi
      - uses: ./.github/actions/pulumi
        with:
          version: ${{ github.event.inputs.version }}
          token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          config: ${{ secrets.PULUMI_CONFIG }}
          passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          stack: vultr
      - name: Pulumi passphrase
        run: |
          echo "${{ secrets.PULUMI_CONFIG_PASSPHRASE || '' }}" > /tmp/pulumi_passphrase
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: vultr
          work-dir: ./deploy/pulumi
          comment-on-pr: ${{ (github.event_name == 'pull_request' && 'true') || 'false' }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE_FILE: "/tmp/pulumi_passphrase"
