name: LGTM
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: lint:api
        working-directory: ./packages/runner
        run: |
          npm ci --silent --no-audit --no-fund
          npm run lint
      - name: lint:app
        working-directory: ./packages/runner
        run: |
          npm ci --silent --no-audit --no-fund
          npm run lint
      - name: lint:mailer
        working-directory: ./packages/runner
        run: |
          npm ci --silent --no-audit --no-fund
          npm run lint
      - name: lint:runner
        working-directory: ./packages/runner
        run: |
          npm ci --silent --no-audit --no-fund
          npm run lint
  commit:
    name: Conventional Commits check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4


