name: Lint Runner
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  pull_request:
    paths:
      - packages/runner/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/linter
        with:
          package_name: runner
          token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          config: ${{ secrets.PULUMI_CONFIG }}
