name: Lint Commit
on:
  workflow_dispatch:
  push:
    branches:
  pull_request:
jobs:
  lint:
    name: Conventional Commits check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
