name: Preview Pulumi
on:
  workflow_dispatch:
  pull_request:
    paths:
      - deploy/pulumi/**
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache-dependency-path: deploy/pulumi/package-lock.json
      - run: npm ci
        working-directory: ./deploy/pulumi
      - uses: ./.github/actions/pulumi
        with:
          version: ${{ github.event.inputs.version }}
          token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          config: ${{ secrets.PULUMI_CONFIG }}
          stack: vultr
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: vultr
          work-dir: ./deploy/pulumi
          comment-on-pr: true
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
