name: Publish Mailer
on:
  push:
    paths:
      - ./packages/mailer/**
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/publisher
        with:
          package_name: mailer
          token: ${{ secrets.GITHUB_TOKEN }}
          wait_on: Lint Mailer
