name: Publish Mailer
on:
  workflow_dispatch:
  push:
    paths:
      - packages/mailer/**
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/linter
        with:
          package_name: mailer
  publish:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/publisher
        with:
          package_name: mailer
          token: ${{ secrets.GITHUB_TOKEN }}
