name: Publish App
on:
  workflow_dispatch:
  push:
    paths:
      - packages/app/**
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/linter
        with:
          package_name: app
  publish:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/publisher
        with:
          package_name: app
          token: ${{ secrets.GITHUB_TOKEN }}
          args: |
            VITE_KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL || 'https://auth.rnd.lvh.me/' }}
            VITE_KEYCLOAK_REALM=rnd
            VITE_KEYCLOAK_CLIENT_ID=rnd-client
