name: Publish Runner
on:
  workflow_dispatch:
  push:
    paths:
      - packages/runner/**
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/tester
        with:
          package_name: runner
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/publisher
        with:
          package_name: runner
          token: ${{ secrets.GITHUB_TOKEN }}
