name: Test Mailer
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  pull_request:
    paths:
      - packages/mailer/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/linter
        with:
          package_name: mailer
