name: Test API
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  pull_request:
    paths:
      - packages/api/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/tester
        with:
          package_name: api
          coverage_token: ${{ secrets.CODECOV_TOKEN }}
